### ISSUE TITLE
Package for Debian?

### ISSUE THREAD

**Issue by petterreinholdtsen** [transcribee/transcribee#127]
Hi.  Do you believe the code base of transcribee is in a state where it make sense to package it for Debian and make it available via the Debian package archive?  Are you interested in helping to make this happen?

**Comment by pajowu** [comment]
Thank you for your interest. I think at the moment transcribee is developing too fast to be packaged, but at some point this would be good

**Comment by petterreinholdtsen** [comment]
[pajowu]
> Thank you for your interest. I think at the moment transcribee is
> developing too fast to be packaged, but at some point this would be
> good

Note, in my experience, it is wise to start packaging early as it guide
how the code and build is structured in a better way.  Also, getting a
package into the quality assurance framework of Debian can help a lot
with both code and licensing quality, and might lift the project at an
early stage.

One do not have to include the package in a stable release, which would
be problematic if there are none willing to support security issues for
2-4 years on the released edition.  It could stay in the unstable/Sid
rolling release until the code base is deemed stable enough for a stable
release schedule.

I would be happy to help get the package into Debian, but do not see the
point if you do not find it useful.

-- 
Happy hacking
Petter Reinholdtsen
