### ISSUE TITLE
Add colors for speakers

### ISSUE THREAD

**Issue by anuejn** [transcribee/transcribee#147]

**Comment by pajowu** [comment]
For audapolis we used the following colors:

* [Dark Mode](https://github.com/audapolis/audapolis/blob/ff91a2c23c31a8179c3d12f348eb91431d0dfb2b/app/src/components/theme.ts#L30)
* [Light Mode](https://github.com/audapolis/audapolis/blob/ff91a2c23c31a8179c3d12f348eb91431d0dfb2b/app/src/components/theme.ts#L126)
