### ISSUE TITLE
Evaluate CRDTs

### ISSUE THREAD

**Issue by pajowu** [transcribee/transcribee#16]
We currently have an editor based on the Yjs CRDT. We want to evaluate other CRDTs as well, before committing to one.

Requirements:
* Works with TypeScript
* Works with Python
* Works with slate
* Fast enough for editing a longer document

Nice-to-Have:
* Existing TS&Py-Bindings
* Easy way to inspect the history of a document and to roll back to specific versions

Possible Candidates:
* Yjs
* Automerge
* [your candidate here]

**Comment by anuejn** [comment]
We are pretty settled on automerge by now
