### ISSUE TITLE
Count task fails/reassignments, mark task as perma-failed

### ISSUE THREAD

**Issue by pajowu** [transcribee/transcribee#248]
Some tasks crash every time. We should add a heuristic to find these task and stop trying them. I propose:

1. If the worker crashes it should report the task back as failed, possibly including logs.
2. If the backend re-assigns a task to a worker, it should mark the task as failed.
3. For that, we should store the task attempts in the db and keep old attempts for later analysis.
4. If a task failed more than X times, it should be marked as permanently failed and not be assigned to workers again.
5. A cli tool should be added to remove the "permanently failed" mark from a task so worker can try it again

**Comment by rroohhh** [comment]
This should probably also get fed back to the frontend somehow, otherwise the user wil just see stuck tasks
