### ISSUE TITLE
Recombine paragraphs

### ISSUE THREAD

**Issue by pajowu** [transcribee/transcribee#56]
We currently use the paragraphs generated by whisper.cpp more or less directly. In my experience this often splits sentences into one long paragraph and a short one only containing the last few words.

It's probably a good idea to recombine these segments using some kind of heuristic (one possible heuristic: If a paragraph is exactly the token limit, does not end with punctuation and the next paragraph ends with punctuation, recombine them)

See also the discussion: https://github.com/transcribee/transcribee/pull/49#discussion_r1154485213

**Comment by anuejn** [comment]
closed by #112 ?

**Comment by anuejn** [comment]
Edit: No, it is not. We still probably want to recombine closer to the sentences
